/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e55338952a8e9561a0d078c
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { SearchService } from '../../services/search.service';
// Import Models
import { Search } from '../../domain/security_db/search';

// START - USED SERVICES
/**
* SearchService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* SearchService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Search
 * @class SearchListComponent
 */
@Component({
    selector: 'app-search-list',
    templateUrl: './search-list.component.html',
    styleUrls: ['./search-list.component.css']
})
export class SearchListComponent implements OnInit {
    list: Search[];
    search: any = {};
    idSelected: string;
    constructor(
        private searchService: SearchService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.searchService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Search to remove
     *
     * @param {string} id Id of the Search to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Search
     */
    deleteItem() {
        this.searchService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
