/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e55338952a8e9561a0d078c
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE securityBaseService PLEASE EDIT ../security.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Security } from '../../domain/security_db/security';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Security.service.ts
 */

/*
 * SCHEMA DB Security
 *
	{
		Distance: {
			type: 'Number'
		},
		Name: {
			type: 'String'
		},
		Place: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Search: [{
			type: Schema.ObjectId,
			ref : "Security"
		}],
		Search: [{
			type: Schema.ObjectId,
			ref : "Search"
		}],
		Security: {
			type: Schema.ObjectId,
			ref : "Security"
		},
	}
 *
 */
@Injectable()
export class SecurityBaseService {

    contextUrl: string = environment.endpoint + '/security';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * SecurityService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Security): Observable<Security> {
        return this.http
            .post<Security>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * SecurityService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * SecurityService.findBySecurity
    *   @description CRUD ACTION findBySecurity
    *   @param Objectid key Id of model to search for
    *
    */
    findBySecurity(id: string): Observable<Security[]> {
        return this.http
            .get<Security[]>(this.contextUrl + '/findBySecurity/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * SecurityService.get
    *   @description CRUD ACTION get
    *   @returns Security
    *
    */
    get(id: string): Observable<Security> {
        return this.http
            .get<Security>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * SecurityService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Security[]> {
        return this.http
            .get<Security[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * SecurityService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Security): Observable<Security> {
        return this.http
            .post<Security>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
