/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e55338952a8e9561a0d078c
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { SecurityService } from '../../services/security.service';
import { SearchService } from '../../services/search.service';
// Import Models
import { Security } from '../../domain/security_db/security';
import { Search } from '../../domain/security_db/search';

// START - USED SERVICES
/**
* SecurityService.create
*	@description CRUD ACTION create
*
* SecurityService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
* SecurityService.get
*	@description CRUD ACTION get
*	@returns Security
*
* SearchService.list
*	@description CRUD ACTION list
*
* SecurityService.list
*	@description CRUD ACTION list
*
* SearchService.findBySearch
*	@description CRUD ACTION findBySearch
*	@param Objectid key Id of model to search for
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Security
 */
@Component({
    selector: 'app-security-edit',
    templateUrl: 'security-edit.component.html',
    styleUrls: ['security-edit.component.css']
})
export class SecurityEditComponent implements OnInit {
    item: Security;
    listSearch: Security[];
    listSecurity: Search[];
    externalSearch_Search: Search[];
    model: Security;
    formValid: Boolean;

    constructor(
    private securityService: SecurityService,
    private searchService: SearchService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Security();
        this.externalSearch_Search = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.securityService.get(id).subscribe(item => this.item = item);
                this.searchService.findBySearch(id).subscribe(list => this.externalSearch_Search = list);
            }
            // Get relations
            this.securityService.list().subscribe(list => this.listSearch = list);
            this.searchService.list().subscribe(list => this.listSecurity = list);
        });
    }

    /**
     * Check if an Security is in  Search
     *
     * @param {string} id Id of Security to search
     * @returns {boolean} True if it is found
     */
    containSecurity(id: string): boolean {
        if (!this.item.Search) return false;
        return this.item.Search.indexOf(id) !== -1;
    }

    /**
     * Add Security from Security
     *
     * @param {string} id Id of Security to add in this.item.Search array
     */
    addSecurity(id: string) {
        if (!this.item.Search)
            this.item.Search = [];
        this.item.Search.push(id);
    }

    /**
     * Remove an Security from a Security
     *
     * @param {number} index Index of Security in this.item.Search array
     */
    removeSecurity(index: number) {
        this.item.Search.splice(index, 1);
    }

    /**
     * Save Security
     *
     * @param {boolean} formValid Form validity check
     * @param Security item Security to save
     */
    save(formValid: boolean, item: Security): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.securityService.update(item).subscribe(data => this.goBack());
            } else {
                this.securityService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



