/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e55338952a8e9561a0d078c
*
* You will get 10% discount for each one of your friends
* 
*/
package com.security.db.security_db.service.base;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.stereotype.Service;

import com.security.db.security_db.mapper.Search;
import com.security.db.security_db.service.SearchService;

@Service
public class SearchBaseService {

	private static NamedParameterJdbcTemplate jdbcTemplate;

	@Autowired
	public void setDataSource(DataSource dataSource) {
		jdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
	}


    //CRUD METHODS
    
    
    //CRUD - CREATE
    	
	public Search insert(Search obj) {
		
		long id = jdbcTemplate.queryForObject("SELECT nvl(max(\"id\")+1, 1) FROM Search", new MapSqlParameterSource(), Long.class);
		obj.set_id(id);
		
		String sql = "INSERT INTO Search (\"id\", \"Distance\",\"Place\"  )	VALUES (:id, :Distance,:Place  )";

		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id)
			.addValue("Distance", obj.getDistance())
			.addValue("Place", obj.getPlace());

		jdbcTemplate.update(sql, parameters);
	    return obj;
	}
	
    	
        	
    //CRUD - REMOVE
    
	public void delete(Long id) {
		String sql = "DELETE FROM Search WHERE \"id\"=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
		
		jdbcTemplate.update(sql, parameters);
	}

    	
        
    //CRUD - FIND BY Search
    	
	public List<Search> findBySearch(Long idSearch) {
		
        String sql = "select * from Search WHERE \"id\" IN (SELECT \"id_Search\" FROM Search_Search WHERE \"id_Security\" = :idSearch)";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
		.addValue("idSearch", idSearch);
	    
	    return jdbcTemplate.query(sql, parameters, new Search());
	}
	
    	
        	
    //CRUD - GET ONE
    	
	public Search get(Long id) {
	    
		String sql = "select * from Search where \"id\" = :id";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
	    
	    return jdbcTemplate.queryForObject(sql, parameters, new Search());
	}

    	
        	
    //CRUD - GET LIST
    	
	public List<Search> getList() {
	    
		String sql = "select * from Search";
		
	    SqlParameterSource parameters = new MapSqlParameterSource();
	    return jdbcTemplate.query(sql, parameters, new Search());
	}

    	
        
    //CRUD - EDIT
    	
	public Search update(Search obj, Long id) {

		String sql = "UPDATE Search SET \"Distance\" = :Distance,\"Place\" = :Place  WHERE \"id\"=:id";

		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id)
			.addValue("Distance", obj.getDistance())
			.addValue("Place", obj.getPlace());

		jdbcTemplate.update(sql, parameters);
	    return obj;
	}
	
    	
        	
    
    
    
    
    // External relation m:m Search
    public static class Search_SearchService {

    	public static ArrayList<Long> findBy_Search(Long id_Search) {
    		String sql = "select \"id_Security\" from Search_Search WHERE \"id_Search\"=:id_Search";
    		SqlParameterSource parameters = new MapSqlParameterSource()
    			.addValue("id_Search", id_Search);
    	    
    	    List<Long> listId = jdbcTemplate.queryForList(sql, parameters, Long.class);
    		return (ArrayList<Long>) listId;
    	}
    	

    	public static void updateRelation(Long id_Search, ArrayList<Long> Search) {

    		// Delete not in array
    		String in = " and \"id_Security\" NOT IN (:Search)";
    		String sql = "DELETE FROM Search_Search WHERE \"id_Search\"=:id_Search ";
    		
    		if (Search != null && Search.size() > 0)
    			sql = sql + in;
    			
    		SqlParameterSource parameters = new MapSqlParameterSource()
    			.addValue("id_Search", id_Search)
    			.addValue("Search", Search);
    		
    		jdbcTemplate.update(sql, parameters);
    		
    		// Get actual    		
    	    List<Long> actual = SearchService.Search_SearchService.findBy_Search(id_Search);
    	    
    		// Insert new
    		for (Long id_Security : Search) {
    			if (actual.indexOf(id_Security) == -1){
    				SearchService.Search_SearchService.insert(id_Search, id_Security);
    			}
    		}
    		
    	}
    	

    	public static void insert(Long id_Search, Long id_Security) {
    		Search.Search_Search obj = new Search.Search_Search();
			Long id = jdbcTemplate.queryForObject("SELECT nvl(max(\"id\")+1, 1) FROM Search_Search", new MapSqlParameterSource(), Long.class);
			obj.set_id(id);
			
			String sql = "INSERT INTO Search_Search (\"id\", \"id_Search\", \"id_Security\" )	VALUES (:id, :id_Search, :id_Security)";

			MapSqlParameterSource parameters = new MapSqlParameterSource()
				.addValue("id", id)
				.addValue("id_Search", id_Search)
				.addValue("id_Security", id_Security);

			jdbcTemplate.update(sql, parameters);
    	}

    }
	    
    
    
    /*
     * CUSTOM SERVICES
     * 
     *	These services will be overwritten and implemented in  Custom.js
     */
    
    
    /*
    Name: validate
    Description: user to search the place
    Params: 
    */
    


}
