/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e55338952a8e9561a0d078c
*
* You will get 10% discount for each one of your friends
* 
*/
package com.security.db.security_db.service.base;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.stereotype.Service;

import com.security.db.security_db.mapper.Security;
import com.security.db.security_db.service.SecurityService;

@Service
public class SecurityBaseService {

	private static NamedParameterJdbcTemplate jdbcTemplate;

	@Autowired
	public void setDataSource(DataSource dataSource) {
		jdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
	}


    //CRUD METHODS
    
    
    //CRUD - CREATE
    	
	public Security insert(Security obj) {
		
		long id = jdbcTemplate.queryForObject("SELECT nvl(max(\"id\")+1, 1) FROM Security", new MapSqlParameterSource(), Long.class);
		obj.set_id(id);
		
		String sql = "INSERT INTO Security (\"id\", \"Distance\",\"Name\",\"Place\" , \"Security\" )	VALUES (:id, :Distance,:Name,:Place , :Security  )";

		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id)
			.addValue("Distance", obj.getDistance())
			.addValue("Name", obj.getName())
			.addValue("Place", obj.getPlace())
			.addValue("Security", obj.getSecurity());

		jdbcTemplate.update(sql, parameters);
	    return obj;
	}
	
    	
        	
    //CRUD - REMOVE
    
	public void delete(Long id) {
		String sql = "DELETE FROM Security WHERE \"id\"=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
		
		jdbcTemplate.update(sql, parameters);
	}

    	
        
    //CRUD - FIND BY Security
    	
	public List<Security> findBySecurity(Long idSecurity) {
		
		String sql = "select * from Security WHERE \"Security\" = :idSecurity";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
		.addValue("idSecurity", idSecurity);
	    
	    return jdbcTemplate.query(sql, parameters, new Security());
	}
	
    	
        	
    //CRUD - GET ONE
    	
	public Security get(Long id) {
	    
		String sql = "select * from Security where \"id\" = :id";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
	    
	    return jdbcTemplate.queryForObject(sql, parameters, new Security());
	}

    	
        	
    //CRUD - GET LIST
    	
	public List<Security> getList() {
	    
		String sql = "select * from Security";
		
	    SqlParameterSource parameters = new MapSqlParameterSource();
	    return jdbcTemplate.query(sql, parameters, new Security());
	}

    	
        
    //CRUD - EDIT
    	
	public Security update(Security obj, Long id) {

		String sql = "UPDATE Security SET \"Distance\" = :Distance,\"Name\" = :Name,\"Place\" = :Place , \"Security\" = :Security  WHERE \"id\"=:id";

		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id)
			.addValue("Distance", obj.getDistance())
			.addValue("Name", obj.getName())
			.addValue("Place", obj.getPlace())
			.addValue("Security", obj.getSecurity());

		jdbcTemplate.update(sql, parameters);
	    return obj;
	}
	
    	
    
    
    
    
    // External relation m:m Search
    public static class Security_SearchService {

    	public static ArrayList<Long> findBy_Security(Long id_Security) {
    		String sql = "select \"id_Security\" from Security_Search WHERE \"id_Security\"=:id_Security";
    		SqlParameterSource parameters = new MapSqlParameterSource()
    			.addValue("id_Security", id_Security);
    	    
    	    List<Long> listId = jdbcTemplate.queryForList(sql, parameters, Long.class);
    		return (ArrayList<Long>) listId;
    	}
    	

    	public static void updateRelation(Long id_Security, ArrayList<Long> Search) {

    		// Delete not in array
    		String in = " and \"id_Security\" NOT IN (:Search)";
    		String sql = "DELETE FROM Security_Search WHERE \"id_Security\"=:id_Security ";
    		
    		if (Search != null && Search.size() > 0)
    			sql = sql + in;
    			
    		SqlParameterSource parameters = new MapSqlParameterSource()
    			.addValue("id_Security", id_Security)
    			.addValue("Search", Search);
    		
    		jdbcTemplate.update(sql, parameters);
    		
    		// Get actual    		
    	    List<Long> actual = SecurityService.Security_SearchService.findBy_Security(id_Security);
    	    
    		// Insert new
    		for (Long id_Security : Search) {
    			if (actual.indexOf(id_Security) == -1){
    				SecurityService.Security_SearchService.insert(id_Security, id_Security);
    			}
    		}
    		
    	}
    	

    	public static void insert(Long id_Security, Long id_Security) {
    		Security.Security_Search obj = new Security.Security_Search();
			Long id = jdbcTemplate.queryForObject("SELECT nvl(max(\"id\")+1, 1) FROM Security_Search", new MapSqlParameterSource(), Long.class);
			obj.set_id(id);
			
			String sql = "INSERT INTO Security_Search (\"id\", \"id_Security\", \"id_Security\" )	VALUES (:id, :id_Security, :id_Security)";

			MapSqlParameterSource parameters = new MapSqlParameterSource()
				.addValue("id", id)
				.addValue("id_Security", id_Security)
				.addValue("id_Security", id_Security);

			jdbcTemplate.update(sql, parameters);
    	}

    }
	    
        
    
    
    /*
     * CUSTOM SERVICES
     * 
     *	These services will be overwritten and implemented in  Custom.js
     */
    


}
